version: '3.7'

services:
  be-talis5-chg:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${PRODUCTION_PORT}:${PRODUCTION_PORT}"
    volumes:
      - ./src:/app/src

volumes:
  talis5-chg-volume: