version: '3.7'

services:
  be-talis5-chg:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "${PRODUCTION_PORT}:${PRODUCTION_PORT}"
