version: '3.7'

services:
  be-talis5-chg:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${PRODUCTION_PORT}:${PRODUCTION_PORT}"
    volumes:
      - ./src:/app/src
      - node_modules:/app/node_modules

volumes:
  node_modules: